robot:
  rate: 50
  arm1:
    controller: 'arm'
    base:
      actuator:
        controller: 'motor'
        topic: 'robot/pwm'
        lpwm: 0
        rpwm: 1
        minPwm: 64
        maxPwm: 255
        minVelocity: 0.0
        maxVelocity: 1.0
        pid:
          p: 0.4079
          i: 0.05242
          d: 0.1964
          i_clamp: 1.0
      encoder:
        controller: 'encoder'
        topic: 'robot/adc'
        channel: 0
        minReading: 810
        maxReading: 258
        minPos: 0
        maxpos: 1
        threshold: 8
        average: 2
    upperarm_actuator:
      actuator:
        controller: 'motor'
        topic: 'robot/pwm'
        lpwm: 2
        rpwm: 3
        minPwm: 32
        maxPwm: 255
        minVelocity: 0.0
        maxVelocity: 1.0
        pid:
          p: 3.149
          i: 4.687
          d: 0.03102
          i_clamp: 1.0
      encoder:
        controller: 'encoder'
        topic: 'robot/adc'
        channel: 1
        minReading: 857
        maxReading: 902
        minPos: 0
        maxPos: 1
        threshold: 8
        average: 2
    forearm_actuator:
      actuator:
        controller: 'motor'
        topic: 'robot/pwm'
        lpwm: 4
        rpwm: 5
        minPwm: 200
        maxPwm: 255
        minVelocity: 0.0
        maxVelocity: 1.0
        pid:
          p: 31.12
          i: 10.22
          d: 0.3102
          i_clamp: 1.0
      encoder:
        controller: 'encoder'
        topic: 'robot/adc'
        channel: 2
        minReading: 976
        maxReading: 848
        minPos: -0.0508
        maxPos: 0
        threshold: 8
        average: 8
    wrist:
      controller: 'solenoid'
      topic: 'robot/pwm'
      channel: 6
