robot:
  publish_rate: 50
  arm1:
    base:
      actuator:
        controller: 'motor'
        enable: true
        topic: 'pwm'
        lpwm: 1
        rpwm: 0
        minPwm: 64
        maxPwm: 255
        minVelocity: 0.0
        maxVelocity: 1.0
      encoder:
        controller: 'encoder'
        enable: true
        topic: 'adc'
        absoluteChannel: 0
        quadratureChannel: 8
        quadratureScale: -0.136820926
        minReading: 283
        maxReading: 771
        minPos: -1.5708
        maxPos: 1.5708
        threshold: 8
        average: 2
    upperarm_actuator:
      actuator:
        controller: 'motor'
        enable: true
        topic: 'pwm'
        lpwm: 2
        rpwm: 3
        minPwm: 32
        maxPwm: 255
        minVelocity: 0.0
        maxVelocity: 1.0
      encoder:
        controller: 'encoder'
        enable: true
        topic: 'adc'
        absoluteChannel: 1
        minReading: 857
        maxReading: 902
        minPos: -0.054
        maxPos: -0.0005
        threshold: 8
        average: 2
    forearm_actuator:
      actuator:
        controller: 'motor'
        enable: true
        topic: 'pwm'
        lpwm: 4
        rpwm: 5
        minPwm: 200
        maxPwm: 255
        minVelocity: 0.0
        maxVelocity: 1.0
      encoder:
        controller: 'encoder'
        enable: true
        topic: 'adc'
        absoluteChannel: 2
        minReading: 976
        maxReading: 848
        minPos: -0.0508
        maxPos: 0
        threshold: 8
        average: 2
    solenoid:
      actuator:
        controller: 'solenoid'
        enable: true
        topic: 'pwm'
        channel: 6
        triggerSeconds: 0.023
