name=Str1ker Firmware Private Library
version=1.0.0
author=01 Binary
maintainer=Valeriy Novytskyy <valeriy.novytskyy@01binary.us>
sentence=Common firmware modules for Str1ker robot
paragraph=Common firmware modules for Str1ker robot
category=Device Control
url=https://github.com/01binary/str1ker
architectures=*
depends=ShiftRegister74HC595,AccelStepper,Encoder,Adafruit BNO055,Adafruit PWM Servo Driver Library,Adafruit INA260 Library
